### ISSUE TITLE
The original questions dataset 

### ISSUE THREAD

**Issue by danyaljj** [dml-qom/FarsTail#2]
Salaam, 

Nice work! 

Questions for you: 
 1. Wondering if you're going to release the original set of questions? 
 2. What version of BERT did you use? (was it fine-tuned on Persian)
 3. Have you tried mBERT (multi-lingual BERT) or XLM-R (https://ai.facebook.com/blog/-xlm-r-state-of-the-art-cross-lingual-understanding-through-self-supervision/)?

**Comment by hossein-amirkhani** [comment]
Hi,

Thanks for your comment.

1. We plan to release the original questions in the MRC format along with the results of some baseline and SOTA methods. This lasts a couple of months. 

2. We used [this version](https://github.com/imgarylai/bert-embedding) of BERT as mentioned in the manuscript. It is used as is without fine-tuning.

3. Not yet.

**Comment by danyaljj** [comment]
> We used this version of BERT as mentioned in the manuscript. It is used as is without fine-tuning. 

Might be good to try this model as well:  
 - https://github.com/hooshvare/parsbert 
 - https://huggingface.co/HooshvareLab/bert-base-parsbert-uncased

**Comment by hossein-amirkhani** [comment]
In the revised version of the manuscript, we fine-tuned both mBERT and ParsBERT, where mBERT was superior. The accuracy obtained through fine-tuning was clearly improved.

**Comment by danyaljj** [comment]
Glad to hear! :)
