### ISSUE TITLE
LICENSE 

### ISSUE THREAD

**Issue by danyaljj** [dml-qom/FarsTail#3]
@h-amirkhani @m-azari nice work! 👏 

We're interested in using your data, and hence, we want to check in with you about its license. 
Could you please add [the license terms](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository) to your github repository? 
A more permissive license that allows us to *modify+redistribute* your dataset (e.g., [Apache 2.0](https://github.com/moby/moby/blob/master/LICENSE)) would work well for us. 

FYI @armancohan

**Comment by hossein-amirkhani** [comment]
Done! Thanks for your interest.
